name: Build xp-apps and components

on:
  push:
    branches:
      - development
      - https-issue

jobs:
  build_debug:
    runs-on: windows-2019
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: nuget restore

      - name: Build Debug (any cpu)
        run: msbuild /t:Build /p:Configuration=Debug /p:Platform="Any CPU"

      - name: Create output directory
        run: mkdir xp-apps\Debug

      - name: Install 7-Zip
        run: |
          choco install 7zip -y
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          RefreshEnv

      - name: Download and unpack curl
        run: |
          Invoke-WebRequest -Uri "https://winampplugins.co.uk/curl/curl_7_46_0_openssl_nghttp2_x86.7z" -OutFile "curl.7z"
          7z x -o"curl_temp" curl.7z 
          mkdir xp-apps\Debug\curl
          move curl_temp\curl.exe xp-apps\Debug\curl\
          move curl_temp\ca-bundle.crt xp-apps\Debug\curl\
          Remove-Item -Recurse -Force curl_temp


      - name: Copy Debug artifacts
        run: |
          xcopy bin\Debug\*.dll xp-apps\Debug /Y
          xcopy bin\Debug\xp-apps.exe xp-apps\Debug /Y
          xcopy Updater\bin\Debug\*.dll xp-apps\Debug /Y
          xcopy Updater\bin\Debug\Updater.exe xp-apps\Debug /Y

      - name: Publish Debug any cpu artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Debug
          path: xp-apps\Debug
  
  build_release:
    runs-on: windows-2019
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: nuget restore

      - name: Build Release (any cpu)
        run: msbuild /t:Build /p:Configuration=Release /p:Platform="Any CPU"

      - name: Create output directory
        run: mkdir xp-apps\Release

      - name: Install 7-Zip
        run: |
          choco install 7zip -y
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          RefreshEnv

      - name: Download and unpack curl
        run: |
          Invoke-WebRequest -Uri "https://winampplugins.co.uk/curl/curl_7_46_0_openssl_nghttp2_x86.7z" -OutFile "curl.7z"
          7z x -o"curl_temp" curl.7z 
          mkdir xp-apps\Release\curl
          move curl_temp\curl.exe xp-apps\Release\curl\
          move curl_temp\ca-bundle.crt xp-apps\Release\curl\
          Remove-Item -Recurse -Force curl_temp


      - name: Copy Release artifacts
        run: |
          xcopy bin\Release\*.dll xp-apps\Release /Y
          xcopy bin\Release\xp-apps.exe xp-apps\Release /Y
          xcopy Updater\bin\Release\*.dll xp-apps\Release /Y
          xcopy Updater\bin\Release\Updater.exe xp-apps\Release /Y

      - name: Publish Release any cpu artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: xp-apps\Release
