name: Build on push to development

on:
  push:
    branches:
      - development

jobs:
  build_debug:
    runs-on: windows-2019
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Restore dependencies
      run: nuget restore
    
    - name: Build Debug (any cpu)
      run: msbuild /t:Build /p:Configuration=Debug /p:Platform="Any CPU"
    
    - name: Publish Debug any cpu artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Debug
        path: |
          bin\Debug\DotNetZip.dll
          bin\Debug\Newtonsoft.Json.dll
          bin\Debug\xp-apps.exe
          bin\Debug\Updater.exe
          bin\Debug\NLog.dll
    
  build_release:
    runs-on: windows-2019
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: nuget restore
    
    - name: Build Release (any cpu)
      run: msbuild /t:Build /p:Configuration=Release /p:Platform="Any CPU"
    
    - name: Publish Release any cpu artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Release
        path: |
          bin\Release\DotNetZip.dll
          bin\Release\Newtonsoft.Json.dll
          bin\Release\xp-apps.exe
          bin\Release\Updater.exe
          bin\Release\NLog.dll
